services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chat"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: redpandadata/redpanda:v24.1.2
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:9092
      - --check=false
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health"]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 20s

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s

  api:
    build: ./api-service
    volumes:
      - ./api-service:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  ws:
    build: ./ws-service
    env_file:
      - ./ws-service/.env
    volumes:
      - ./ws-service:/app
      - go_mod_cache:/go/pkg/mod
    expose:
      - "8080"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  message:
    build: ./message-service
    env_file:
      - ./message-service/.env
    volumes:
      - ./message-service:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "5173:5173"

  migrations:
    image: kukymbr/goose-docker:3.27.0
    depends_on:
      - postgres
    volumes:
      - ./db/migrations:/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=postgres port=5432 user=postgres password=postgres dbname=chat sslmode=disable
      GOOSE_COMMAND: up
    restart: "no"

  ws-lb:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/ws.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ws

volumes:
  postgres_data:
  kafka_data:
  redis_data:
  node_modules_cache:
  go_mod_cache: