services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  kafka:
    image: redpandadata/redpanda:v24.1.2
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:9092
      - --check=false
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/redpanda/data

  api:
    build: ./api-service
    volumes:
      - ./api-service:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  ws:
    build: ./ws-service
    volumes:
      - ./ws-service:/app
      - go_mod_cache:/go/pkg/mod
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  message:
    build: ./message-service
    volumes:
      - ./message-service:/app
      - go_mod_cache:/go/pkg/mod
    depends_on:
      - kafka
      - postgres

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_data:
  kafka_data:
  node_modules_cache:
  go_mod_cache: